{% set name = "azure-mgmt-datafactory" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-datafactory-{{ version }}.zip
  sha256: bc2560b4de1528292883b53a337b89f04a5ceab7c3500b6bc388e3a77ff093cc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - azure
    - pip
  run:
    - python >=3.5
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0.0
    - msrest >=0.5.0

test:
  imports:
    - azure.mgmt.datafactory
    - azure.mgmt.datafactory.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Data Factory Management Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
