{% set name = "azure-mgmt-datafactory" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-datafactory-{{ version }}.zip
  sha256: a6306314f90a84a77c5c8eb09b35ffac0b2c1c834ccc30196be5d1a86fe92d8a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure.mgmt.datafactory
    - azure.mgmt.datafactory.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Data Factory Management Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
