{% set name = "azure-mgmt-datafactory" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-datafactory-{{ version }}.zip
  sha256: c2af20ff178a328e05fe11bb5d5378b3cc38f637dd34de1c8530b32115948695

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - msrest >=0.7.1

test:
  imports:
    - azure.mgmt.datafactory
    - azure.mgmt.datafactory.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Data Factory Management Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
